### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by dsfx3d** [dsfx3d/issue-progress-notifier#5]
- [ ] fetch issue via GitHub's GraphQL API
- [ ] create an `ejs` template for email body
- [ ] use inline `@primer/css` for styling the template
- [ ] compile the template with issue data
- [ ] purge unused css
- [ ] add tests
- [ ] add AWS SES and send email
- [ ] create a GitHub action for the workflow
